### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by SonicandTailsCD** [itsnebulalol/ding#1]
![D5BA2464-A4C5-4B37-8D6A-4B96767544D7](https://github.com/itsnebulalol/ding/assets/80169260/a824b3ae-fb99-4ee7-8034-4de75903d779)
Couldn't compile the source :(
What do I do? :/

**Comment by itsnebulalol** [comment]
No support will be provided for compiling it yourself. You may purchase it on [Chariz](https://chariz.com/buy/ding).

**Comment by SonicandTailsCD** [comment]
I feel like that's kinda unfair on your part, because at least basic support should be provided, but I understand and won't argue further.
Have a good day :)

(Next time PLEASE do not close these kinds of requests as completed, close them as not planned to avoid confusion.)

**Comment by itsnebulalol** [comment]
> I feel like that's kinda unfair on your part

Sure I guess, but you didn’t follow the commands I put in the readme.

And thanks, I will close it as not planned.

**Comment by SonicandTailsCD** [comment]
> > I feel like that's kinda unfair on your part
> 
> Sure I guess, but you didn’t follow the commands I put in the readme.

Actually, I did follow the commands you mentioned in the readme file but nothing worked :/

> And thanks, I will close it as not planned.

No prob, just trying to help out fellow GitHub devs :D 
And to avoid spam/unnecessary arguments, this will be my LAST comment under this issue (unless mentioned with @SonicandTailsCD). So reply at your wish, but I won't respond unless my name is mentioned. Have a good day :)
